vich_uploader:
    db_driver: orm
    metadata:
         type: attribute

    mappings:
       produits_images:
           uri_prefix: /images/produit
           upload_destination: "%kernel.project_dir%/public/images/produit"
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
